export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_QUANTITY_IN_CART = 'UPDATE_QUANTITY_IN_CART'
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE'